import { Card, Attribute, Rarity } from './types';

const EMOJI_MAP: Record<string, string[]> = {
  fire: ['🔥', '🌋', '☄️', '💥', '🐲'],
  water: ['🌊', '💧', '🐟', '🐳', '🦈'],
  grass: ['🌿', '🍀', '🌳', '🦎', '🐛'],
  thunder: ['⚡', '🌩️', '💫', '🦅', '🐆'],
  dark: ['🌑', '👻', '🦇', '💀', '🐺'],
  light: ['✨', '🌟', '👼', '🦋', '🌈'],
};

function getEmoji(attr: string, id: number): string {
  const emojis = EMOJI_MAP[attr] || ['❓'];
  return emojis[id % emojis.length];
}

export const CARDS: Card[] = [
  {id:1,name:'グリムシェイド',attr:'dark',rarity:'SR',hp:200,atk:95,spd:88,skill:'シャドウクロウ',emoji:''},
  {id:2,name:'サンダードレイク',attr:'thunder',rarity:'SR',hp:190,atk:100,spd:95,skill:'ライトニングバイト',emoji:''},
  {id:3,name:'ライガロン',attr:'fire',rarity:'SR',hp:160,atk:92,spd:78,skill:'インフェルノロアー',emoji:''},
  {id:4,name:'フロストクイーン',attr:'dark',rarity:'SR',hp:155,atk:80,spd:72,skill:'アイスブリザード',emoji:''},
  {id:5,name:'ナイトバット',attr:'dark',rarity:'SR',hp:170,atk:85,spd:80,skill:'シャドウダイブ',emoji:''},
  {id:6,name:'キングシャーク',attr:'water',rarity:'SR',hp:165,atk:90,spd:90,skill:'ロイヤルバイト',emoji:''},
  {id:7,name:'ゴールデンフェニックス',attr:'thunder',rarity:'SR',hp:158,atk:88,spd:96,skill:'ゴールドフレア',emoji:''},
  {id:8,name:'フォレストスピリット',attr:'grass',rarity:'SR',hp:162,atk:82,spd:65,skill:'ネイチャーストーム',emoji:''},
  {id:9,name:'ブルーウィンド',attr:'thunder',rarity:'SR',hp:150,atk:78,spd:99,skill:'ウィンドダッシュ',emoji:''},
  {id:10,name:'ドロシェル',attr:'grass',rarity:'SR',hp:175,atk:99,spd:40,skill:'アースバンプ',emoji:''},
  {id:11,name:'クラーケン',attr:'water',rarity:'R',hp:120,atk:65,spd:75,skill:'インクスプラッシュ',emoji:''},
  {id:12,name:'サンダーバニー',attr:'thunder',rarity:'R',hp:110,atk:72,spd:90,skill:'エレキホップ',emoji:''},
  {id:13,name:'ダークフェリス',attr:'dark',rarity:'R',hp:135,atk:80,spd:70,skill:'パープルファング',emoji:''},
  {id:14,name:'スノーパンダ',attr:'dark',rarity:'R',hp:130,atk:78,spd:60,skill:'スノーボール',emoji:''},
  {id:15,name:'エメラルドウィング',attr:'thunder',rarity:'R',hp:105,atk:65,spd:88,skill:'ウィンドカッター',emoji:''},
  {id:16,name:'タスマニアン',attr:'grass',rarity:'R',hp:125,atk:75,spd:55,skill:'ラブタックル',emoji:''},
  {id:17,name:'ジェリーグロウ',attr:'water',rarity:'R',hp:115,atk:60,spd:72,skill:'グロウビーム',emoji:''},
  {id:18,name:'フレイムフォックス',attr:'fire',rarity:'R',hp:118,atk:70,spd:85,skill:'ファイアテール',emoji:''},
  {id:19,name:'アクアサーペント',attr:'water',rarity:'R',hp:122,atk:68,spd:78,skill:'アクアコイル',emoji:''},
  {id:20,name:'フォレストフェアリー',attr:'grass',rarity:'R',hp:112,atk:65,spd:70,skill:'ネイチャーブレス',emoji:''},
  {id:21,name:'ホーリーフェニックス',attr:'light',rarity:'R',hp:128,atk:72,spd:80,skill:'セイクリッドウィング',emoji:''},
  {id:22,name:'ブリザードウルフ',attr:'thunder',rarity:'R',hp:132,atk:80,spd:88,skill:'アイスファング',emoji:''},
  {id:23,name:'オーシャンドレイク',attr:'water',rarity:'R',hp:138,atk:82,spd:68,skill:'シースピン',emoji:''},
  {id:24,name:'デモンロード',attr:'grass',rarity:'R',hp:140,atk:88,spd:52,skill:'デモニックグレア',emoji:''},
  {id:25,name:'オルカスター',attr:'water',rarity:'R',hp:125,atk:70,spd:85,skill:'オーシャンスラム',emoji:''},
  {id:26,name:'インフェルノバット',attr:'fire',rarity:'N',hp:85,atk:45,spd:55,skill:'ファイアウィング',emoji:''},
  {id:27,name:'バブロン',attr:'water',rarity:'N',hp:80,atk:40,spd:60,skill:'バブルボム',emoji:''},
  {id:28,name:'フォレストノーム',attr:'grass',rarity:'N',hp:78,atk:38,spd:58,skill:'ハーブバレット',emoji:''},
  {id:29,name:'ライトニングキャット',attr:'thunder',rarity:'N',hp:82,atk:45,spd:72,skill:'スパークキャット',emoji:''},
  {id:30,name:'ヴァンパイアロード',attr:'dark',rarity:'N',hp:76,atk:40,spd:68,skill:'ブラッドファング',emoji:''},
  {id:31,name:'スターキャット',attr:'light',rarity:'N',hp:80,atk:42,spd:68,skill:'スターストライク',emoji:''},
  {id:32,name:'マグマフロッグ',attr:'water',rarity:'N',hp:95,atk:45,spd:30,skill:'ラヴァジャンプ',emoji:''},
  {id:33,name:'スノーペンギン',attr:'thunder',rarity:'N',hp:78,atk:45,spd:82,skill:'アイスメール',emoji:''},
  {id:34,name:'メカビー',attr:'grass',rarity:'N',hp:100,atk:58,spd:28,skill:'ドリルスティング',emoji:''},
  {id:35,name:'アクアタートル',attr:'dark',rarity:'N',hp:72,atk:38,spd:72,skill:'シェルバッシュ',emoji:''},
  {id:36,name:'ダークシャーク',attr:'fire',rarity:'N',hp:88,atk:55,spd:58,skill:'ホーンスラッシュ',emoji:''},
  {id:37,name:'フラワーベア',attr:'water',rarity:'N',hp:82,atk:48,spd:65,skill:'フラワーハグ',emoji:''},
  {id:38,name:'ゲッコーナイト',attr:'grass',rarity:'N',hp:92,atk:58,spd:45,skill:'スケイルスラッシュ',emoji:''},
  {id:39,name:'アクアドラゴン',attr:'thunder',rarity:'N',hp:80,atk:62,spd:85,skill:'バブルブレス',emoji:''},
  {id:40,name:'サンダーフェニックス',attr:'dark',rarity:'N',hp:75,atk:38,spd:45,skill:'ゴールドフレア',emoji:''},
  {id:41,name:'シャドウキャット',attr:'water',rarity:'N',hp:78,atk:45,spd:65,skill:'ダークステップ',emoji:''},
  {id:42,name:'フロストフォックス',attr:'light',rarity:'N',hp:70,atk:38,spd:62,skill:'アイスステップ',emoji:''},
  {id:43,name:'クリスタルサーペント',attr:'dark',rarity:'N',hp:82,atk:48,spd:72,skill:'クリスタルコイル',emoji:''},
  {id:44,name:'アーマービートル',attr:'thunder',rarity:'N',hp:80,atk:50,spd:70,skill:'アイアンホーン',emoji:''},
  {id:45,name:'コスモタコ',attr:'grass',rarity:'N',hp:75,atk:52,spd:50,skill:'コスミックインク',emoji:''},
  {id:46,name:'ダークキュウビ',attr:'thunder',rarity:'N',hp:82,atk:52,spd:60,skill:'ダークテール',emoji:''},
  {id:47,name:'スカルバニー',attr:'grass',rarity:'N',hp:88,atk:58,spd:40,skill:'ゴーストホップ',emoji:''},
  {id:48,name:'サンダーイーグル',attr:'water',rarity:'N',hp:85,atk:58,spd:68,skill:'ライトニングタロン',emoji:''},
  {id:49,name:'アイスベア',attr:'fire',rarity:'N',hp:86,atk:65,spd:82,skill:'バブルハグ',emoji:''},
  {id:50,name:'アンバービートル',attr:'thunder',rarity:'N',hp:78,atk:50,spd:72,skill:'アンバーチャージ',emoji:''},
  {id:51,name:'インヤンドレイク',attr:'fire',rarity:'N',hp:50,atk:28,spd:30,skill:'バランスブレイク',emoji:''},
  {id:52,name:'アクアフロッグ',attr:'water',rarity:'N',hp:52,atk:25,spd:42,skill:'アクアジャンプ',emoji:''},
  {id:53,name:'バトルパンダ',attr:'grass',rarity:'N',hp:48,atk:22,spd:35,skill:'パンダキャノン',emoji:''},
  {id:54,name:'シェルタヌキ',attr:'thunder',rarity:'N',hp:50,atk:28,spd:58,skill:'シェルスピン',emoji:''},
  {id:55,name:'スターバニー',attr:'dark',rarity:'N',hp:55,atk:30,spd:15,skill:'スターシャイン',emoji:''},
  {id:56,name:'ジャングルモンキー',attr:'light',rarity:'N',hp:45,atk:20,spd:45,skill:'バインドバナナ',emoji:''},
  {id:57,name:'スリープボルト',attr:'water',rarity:'N',hp:58,atk:25,spd:20,skill:'スリープボルト',emoji:''},
  {id:58,name:'バブルバード',attr:'thunder',rarity:'N',hp:42,atk:18,spd:48,skill:'バブルフライト',emoji:''},
  {id:59,name:'ファイアベア',attr:'grass',rarity:'N',hp:55,atk:32,spd:28,skill:'ウォームハグ',emoji:''},
  {id:60,name:'アーマースラッグ',attr:'dark',rarity:'N',hp:48,atk:25,spd:55,skill:'アーマーシェル',emoji:''},
  {id:61,name:'クリスタルウィング',attr:'fire',rarity:'N',hp:52,atk:28,spd:10,skill:'プリズムレイ',emoji:''},
  {id:62,name:'パンダモンキー',attr:'water',rarity:'N',hp:45,atk:22,spd:38,skill:'ラブパンチ',emoji:''},
  {id:63,name:'スポットキャット',attr:'grass',rarity:'N',hp:48,atk:22,spd:32,skill:'スポットロール',emoji:''},
  {id:64,name:'フロッグキング',attr:'thunder',rarity:'N',hp:46,atk:25,spd:62,skill:'ロイヤルジャンプ',emoji:''},
  {id:65,name:'グリーンパロット',attr:'dark',rarity:'N',hp:52,atk:28,spd:55,skill:'ミミックスクリーム',emoji:''},
  {id:66,name:'ゴールドドラゴン',attr:'light',rarity:'N',hp:48,atk:22,spd:42,skill:'ゴールデンブレス',emoji:''},
  {id:67,name:'サイバーエイリアン',attr:'water',rarity:'N',hp:50,atk:20,spd:15,skill:'サイバーボルト',emoji:''},
  {id:68,name:'サーフパンダ',attr:'thunder',rarity:'N',hp:42,atk:18,spd:52,skill:'ウェーブライド',emoji:''},
  {id:69,name:'フレイムサーペント',attr:'grass',rarity:'N',hp:45,atk:25,spd:38,skill:'ファイアコイル',emoji:''},
  {id:70,name:'ネオンモス',attr:'dark',rarity:'N',hp:48,atk:22,spd:48,skill:'ネオンダスト',emoji:''},
  {id:71,name:'ツバメナイト',attr:'fire',rarity:'N',hp:46,atk:25,spd:55,skill:'スウィフトダイブ',emoji:''},
  {id:72,name:'プリズムロボ',attr:'water',rarity:'N',hp:55,atk:28,spd:32,skill:'プリズムキャノン',emoji:''},
  {id:73,name:'スポットフロッグ',attr:'grass',rarity:'N',hp:50,atk:18,spd:8,skill:'スポットスピット',emoji:''},
  {id:74,name:'ダークウルフ',attr:'thunder',rarity:'N',hp:48,atk:28,spd:42,skill:'シャドウバイト',emoji:''},
  {id:75,name:'クトゥルフォン',attr:'dark',rarity:'N',hp:45,atk:22,spd:45,skill:'テンタクルウェーブ',emoji:''},
  {id:76,name:'クラウンベア',attr:'light',rarity:'N',hp:48,atk:22,spd:38,skill:'ロイヤルパンチ',emoji:''},
  {id:77,name:'ムーンフォックス',attr:'water',rarity:'N',hp:44,atk:18,spd:32,skill:'ムーンバブル',emoji:''},
  {id:78,name:'インフェルノボム',attr:'thunder',rarity:'N',hp:44,atk:18,spd:55,skill:'ファイアボム',emoji:''},
  {id:79,name:'ナイトクリッター',attr:'grass',rarity:'N',hp:52,atk:25,spd:20,skill:'ダークスクラッチ',emoji:''},
  {id:80,name:'フロストフェニックス',attr:'dark',rarity:'N',hp:50,atk:22,spd:22,skill:'クリスタルウィング',emoji:''},
  {id:81,name:'タヌキング',attr:'fire',rarity:'N',hp:48,atk:25,spd:32,skill:'タヌキポン',emoji:''},
  {id:82,name:'シャドウバニー',attr:'water',rarity:'N',hp:46,atk:20,spd:35,skill:'ダークホップ',emoji:''},
  {id:83,name:'タイキョクバード',attr:'grass',rarity:'N',hp:50,atk:22,spd:30,skill:'バランスフライト',emoji:''},
  {id:84,name:'デモンバック',attr:'thunder',rarity:'N',hp:48,atk:28,spd:40,skill:'アンクルラッシュ',emoji:''},
  {id:85,name:'モノクロキャット',attr:'dark',rarity:'N',hp:50,atk:28,spd:55,skill:'モノトーンクロウ',emoji:''},
  {id:86,name:'ネオンデモン',attr:'light',rarity:'N',hp:44,atk:18,spd:48,skill:'ネオンビーム',emoji:''},
  {id:87,name:'ケープキャット',attr:'water',rarity:'N',hp:46,atk:20,spd:18,skill:'マントスラッシュ',emoji:''},
  {id:88,name:'エナジーモンキー',attr:'thunder',rarity:'N',hp:44,atk:20,spd:55,skill:'エナジースピン',emoji:''},
  {id:89,name:'アームドベア',attr:'grass',rarity:'N',hp:55,atk:32,spd:28,skill:'ボードスマッシュ',emoji:''},
  {id:90,name:'カードドラゴン',attr:'dark',rarity:'N',hp:42,atk:18,spd:30,skill:'カードストライク',emoji:''},
  {id:91,name:'ジュラゴン',attr:'fire',rarity:'N',hp:50,atk:25,spd:48,skill:'ダイノバイト',emoji:''},
  {id:92,name:'ラスカルファング',attr:'water',rarity:'N',hp:48,atk:22,spd:40,skill:'スパイクラッシュ',emoji:''},
  {id:93,name:'スターキティ',attr:'grass',rarity:'N',hp:52,atk:22,spd:18,skill:'スターゲイズ',emoji:''},
  {id:94,name:'フローラサーペント',attr:'thunder',rarity:'N',hp:46,atk:22,spd:25,skill:'フラワーポイズン',emoji:''},
  {id:95,name:'グロウバグ',attr:'dark',rarity:'N',hp:48,atk:22,spd:42,skill:'グロウフラッシュ',emoji:''},
  {id:96,name:'トーチフロッグ',attr:'light',rarity:'N',hp:50,atk:20,spd:15,skill:'トーチブレイズ',emoji:''},
  {id:97,name:'アクアリザード',attr:'water',rarity:'N',hp:46,atk:18,spd:20,skill:'アクアダッシュ',emoji:''},
  {id:98,name:'インフェルノウルフ',attr:'thunder',rarity:'N',hp:42,atk:18,spd:52,skill:'フレイムハウル',emoji:''},
  {id:99,name:'レイブンシャドウ',attr:'grass',rarity:'N',hp:52,atk:22,spd:12,skill:'ダークタロン',emoji:''},
  {id:100,name:'ルミナフワ',attr:'dark',rarity:'N',hp:50,atk:22,spd:55,skill:'ルミナスハグ',emoji:''},
].map(c => ({ ...c, emoji: getEmoji(c.attr, c.id), attr: c.attr as Attribute, rarity: c.rarity as Rarity }));

export const ATTR_NAMES: Record<string, string> = {
  fire: 'ほのお',
  water: 'みず',
  grass: 'くさ',
  thunder: 'かみなり',
  dark: 'やみ',
  light: 'ひかり',
};

export const ATTR_COLORS: Record<string, string> = {
  fire: 'bg-red-500',
  water: 'bg-blue-500',
  grass: 'bg-green-500',
  thunder: 'bg-yellow-500',
  dark: 'bg-purple-700',
  light: 'bg-amber-300',
};

export const ATTR_TEXT_COLORS: Record<string, string> = {
  fire: 'text-red-400',
  water: 'text-blue-400',
  grass: 'text-green-400',
  thunder: 'text-yellow-400',
  dark: 'text-purple-400',
  light: 'text-amber-300',
};

// 属性相性: 1.5倍ダメージになる組み合わせ
export const ATTR_ADVANTAGE: Record<string, string[]> = {
  fire: ['grass'],
  water: ['fire'],
  grass: ['water'],
  thunder: ['water'],
  dark: ['light'],
  light: ['dark'],
};

export function getCardById(id: number): Card | undefined {
  return CARDS.find(c => c.id === id);
}
